[workspace]

members = [
  "apollo-at-link",
  "apollo-federation-error",
  "apollo-harness",
  "apollo-subgraph",
  "apollo-supergraph",
]

default-members = [
  "apollo-at-link",
  "apollo-subgraph",
  "apollo-supergraph",
]

resolver = "2"
