[package]
name = "apollo-federation"
version = "0.0.5"
authors = ["The Apollo GraphQL Contributors"]
edition = "2021"
description = "Apollo Federation"
documentation = "https://docs.rs/apollo-federation"
repository = "https://github.com/apollographql/federation-next"
license = "Elastic-2.0"
autotests = false                                               # Integration tests are modules of tests/main.rs

[dependencies]
apollo-compiler = "=1.0.0-beta.12"
derive_more = "0.99.17"
indexmap = "2.1.0"
lazy_static = "1.4.0"
petgraph = "0.6.4"
salsa = "0.16.1"
serde_json = "1.0.108"
strum = "0.26.0"
strum_macros = "0.25.2"
thiserror = "1.0"
url = "2"

[dev-dependencies]
insta = { version = "1.34.0", features = ["yaml"] }

[[test]]
name = "main"
